repo_name: zkan/thinking-with-data
repo_url: https://github.com/zkan/thinking-with-data
site_name: Thinking with Data
site_url: https://zkan.github.io/thinking-with-data/

theme:
  name: material

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - git-authors:
      show_email_address: false
  - git-revision-date-localized:
      enable_creation_date: false
  - search
